### ISSUE TITLE
点击forum问题

### ISSUE THREAD

**Issue by hoccpan** [yzhao0527/toybox#39]
1）点 Forum，出来很多文章（感觉是所有公开post）
2）然后点 QiShiClub，还是跟点Forum一样的页面
3）然后点 “Machine Learning Group"，出来“This is Header.."页面
4）然后点回 QiShiClub, 还是和3）一样的页面。

**Comment by ciryiping** [comment]
1.目前的forum首页直接显示qishi club，可能需要加一个所有讨论区的页面
2.原理同上，非bug，但需要改进
3.this is header 是一个文章标题。。。
4.qishiclub是标签，不是论坛，以更改名称
